version: "3"

services:
  ws_server:
    container_name: ws_server
    build:
      context: .
      dockerfile: Dockerfile
    image: ws_server
    environment:
      - API_SERVER=${API_SERVER}
    restart: unless-stopped
    ports:
    - "${LOCAL_PORT}:20080"
